- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
  become: true

- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
  become: true
