- name: Copy newpush-lab script
  ansible.builtin.copy:
    src: "../../installer/newpush-lab.sh"
    dest: /usr/local/bin/newpush-lab
    mode: "0755"

- name: Create symlink for student-lab installer
  ansible.builtin.file:
    src: /usr/local/bin/newpush-lab
    dest: /usr/local/bin/lab
    state: link

- name: Copy casdoor utils
  ansible.builtin.copy:
    src: "../../utils/casdoor"
    dest: "{{ lab_dir }}/utils/"
    mode: "0755"
