- name: Update lab
  hosts: lab
  remote_user: root
  roles:
    - common
    - lab-copy-installer
    - lab-copy-dockers
    - lab-install-docker
    - lab-set-permissions
  tasks:
    - name: Run newpush-lab to reconfig
      ansible.builtin.command: /usr/local/bin/newpush-lab reconfig

    - name: Run newpush-lab to stop lab
      ansible.builtin.command: /usr/local/bin/newpush-lab stop newpush-lab

    - name: Run newpush-lab to start lab
      ansible.builtin.command: /usr/local/bin/newpush-lab start newpush-lab
