- name: Reconfigure lab
  hosts: lab
  remote_user: root
  roles:
    - common
    - lab-copy-installer
    - lab-copy-dockers
    - lab-configure-env
    - lab-set-permissions

  tasks:
    - name: Run newpush-lab to reconfig
      ansible.builtin.command: /usr/local/bin/newpush-lab reconfig
