- name: Reconfigure lab
  hosts: lab
  remote_user: root
  roles:
    # - role: common
    # - role: gantsign.golang
    #   golang_gopath: '$HOME/workspace-go'
    - lab-user
    - lab-copy-installer
    - lab-copy-dockers
    - lab-configure-env
    # - lab-configure-security
    # - lab-set-permissions
    # - lab-utils-tty2web
  tasks:
