services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 90s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_NO_ANALYTICS=true
      - DOZZLE_ENABLE_ACTIONS=true
    labels:
      - "com.centurylinklabs.watchtower.enable"
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`logs.${DOMAIN}`)"
      - "traefik.http.routers.dozzle.entrypoints=https"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      - "traefik.http.routers.dozzle.service=dozzle"
      - "traefik.http.routers.dozzle.tls=true"
      - "traefik.http.routers.dozzle.tls.certresolver=default"
      - "traefik.http.routers.dozzle.middlewares=traefik-forward-auth"
      - "mafl.enable=true"
      - "mafl.title=Dozzle"
      - "mafl.description=A lightweight, open-source, and secure log viewer for Docker."
      - "mafl.tag=docker"
      - "mafl.group=Docker"
      - "mafl.link=https://logs.${DOMAIN}"
      - "mafl.icon.name=simple-icons:drizzle"
      - "mafl.icon.wrap=true"
      - "mafl.icon.color=#007acc"
      - "mafl.status.enabled=true"
      - "mafl.status.interval=60"
    # expose:
    #   - 8080
    restart: unless-stopped
    networks:
      - web

# dozzle-from-file:
#   container_name: dozzle-from-file
#   image: alpine
#   volumes:
#     - /var/log/system.log:/var/log/stream.log
#   command:
#     - tail
#     - -f
#     - /var/log/stream.log
#   network_mode: none
#   restart: unless-stopped
networks:
  web:
    external: True
