version: "3.3"

services:
  traefik:
    restart: unless-stopped # this is mine
    image: "traefik:latest"
    env_file:
      - .env
    container_name: "traefik" 
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - "./traefik:/etc/traefik"
      - "./traefik/logs:/var/log/traefik"
      - "./:/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.http.routers.traefik-api.service=api@internal"
      - "traefik.http.routers.traefik-api.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik-api.entrypoints=https"
      - "traefik.http.routers.traefik-api.tls.certresolver=default"
      - "traefik.http.routers.traefik-api.middlewares=traefik-forward-auth"      
    logging:
      driver: journald
    networks:
      - web

networks:
  web:
    external: True