services:
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
      - web
    # ports:
    #   - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://searxng.${DOMAIN}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      - "mafl.enable=true"
      - "mafl.title=SearxNG"
      - "mafl.group=Services"
      - "mafl.description=Private, privacy-respecting, anonymous, and decentralized search engine."
      - "mafl.link=https://searxng.${DOMAIN}/"
      - "mafl.icon.name=icon-park:search"
      - "mafl.icon.wrap=true"
      - "mafl.icon.color=#ffffff"
      - "mafl.status.enabled=true"
      - "mafl.status.interval=60"
      - "com.centurylinklabs.watchtower.enable"
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=Host(`searxng.${DOMAIN}`)"
      - "traefik.http.routers.searxng.entrypoints=https"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"
      - "traefik.http.routers.searxng.service=searxng"
      - "traefik.http.routers.searxng.tls=true"
      - "traefik.http.routers.searxng.tls.certresolver=default"
      - "traefik.http.routers.searxng.middlewares=traefik-forward-auth" 
networks:
  searxng:
  web:
    external: True

volumes:
  valkey-data2:

 