http:
  middlewares:
    sablier-dynamic:
      plugin:
        sablier:
          group: default
          names: whoami
          dynamic:
            displayName: My Title
            refreshFrequency: 5s
            showDetails: "true"
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 1m


