http:
  middlewares:
    sablier-dynamic-whoami:
      plugin:
        sablier:
          group: default
          names: whoami
          dynamic:
            displayName: Whoami
            refreshFrequency: 5s
            showDetails: "true"
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
  services:
    whoami:
      loadBalancer:
        servers:
          - url: "http://whoami:80"
  routers:
    whoami:
      rule: PathPrefix(`/whoami`)
      entryPoints:
        - "https"
      middlewares:
        - sablier-dynamic-whoami@file
      service: "whoami"
      priority: 100
      tls:
        certResolver: default
