apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
  - name: loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    isDefault: false
 