# Default variables for the common role
common_packages:
  - vim
  - curl
  - wget
  - git
  - apt-transport-https
  - ca-certificates
  - gnupg
  - curl
  - rsync
  - "{{ 'python3-software-properties' if (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 13) else 'software-properties-common' }}"
  - ncdu
  - jq
  - ufw
