version: "3"

services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: latest
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    networks:
      - jupyterhub-network
      - web
    volumes:
      # The JupyterHub configuration file
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "jupyterhub-data:/data"
    environment:
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: admin
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: quay.io/jupyter/base-notebook:latest
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
    env_file:
      - /opt/student-lab/services/.env
    labels:
      - "com.centurylinklabs.watchtower.enable"
      - "traefik.enable=true"
      - "traefik.http.routers.jupyterhub.rule=Host(`jupyter-hub.${DOMAIN}`)"
      - "traefik.http.routers.jupyterhub.entrypoints=https"
      - "traefik.http.services.jupyterhub.loadbalancer.server.port=8000"
      - "traefik.http.routers.jupyterhub.service=jupyterhub"
      - "traefik.http.routers.jupyterhub.tls=true"
      - "traefik.http.routers.jupyterhub.tls.certresolver=default"
      - "traefik.http.routers.jupyterhub.middlewares=traefik-forward-auth"
      - "mafl.enable=true"
      - "mafl.title=JupyterHub"
      - "mafl.description=A multi-user version of the notebook designed for companies, classrooms and research labs."
      - "mafl.tag=development"
      - "mafl.group=Development"
      - "mafl.link=https://jupyter-hub.${DOMAIN}"
      - "mafl.icon.name=simple-icons:jupyter"
      - "mafl.icon.wrap=true"
      - "mafl.icon.color=#F37626"
      - "mafl.status.enabled=true"
      - "mafl.status.interval=60"
volumes:
  jupyterhub-data:

networks:
  jupyterhub-network:
    name: jupyterhub-network
  web:
    external: True
