title: newpush labs
theme: dark
layout:
  grid:
    small: 2
    medium: 2
    large: 3
    xlarge: 4
services:
  Cloud:
    - title: Traefik
      description: Cloud edge router
      link: 'https://traefik.${DOMAIN}'
      icon:
        name: devicon:traefikproxy
        wrap: true
      status:
        enabled: true
    - title: Casdoor
      description: An Identity Access Management Platform
      link: 'https://auth.${DOMAIN}'
      icon:
        url: https://cdn.jsdelivr.net/gh/selfhst/icons/png/casdoor.png
        wrap: true
      status:
        enabled: true
  Docker:
    - title: Portainer
      description: Docker container management
      link: 'https://portainer.${DOMAIN}'
      icon:
        name: devicon:portainer
        wrap: true
      status:
        enabled: true
  Monitoring:
    - title: Grafana
      description: Grafana
      link: 'https://grafana.${DOMAIN}'
      icon:
        name: devicon:grafana
        wrap: true
      status:
        enabled: true
  